name: Publish NuGet

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore & Build
        run: |
          dotnet restore src/CosmoBase/CosmoBase.csproj
          dotnet build src/CosmoBase/CosmoBase.csproj --configuration Release

      - name: Pack
        run: |
          dotnet pack src/CosmoBase/CosmoBase.csproj \
            --configuration Release \
            --no-build

      - name: Push to NuGet.org
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          dotnet nuget push src/CosmoBase/bin/Release/*.nupkg \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json
