name: CosmoBase - Publish NuGet Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout full history for GitVersion to work
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Install .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      # 3. Install GitVersion to calculate SemVer from your Git history
      - name: Setup GitVersion
        uses: GitTools/actions/gitversion/setup@v0.9.13
        with:
          versionSpec: '5.x'

      # 4. Restore & build the project
      - name: Run GitVersion
        id: gitversion
        uses: GitTools/actions/gitversion/execute@v0.9.13
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml

      - name: Restore & Build
        run: |
          dotnet restore src/CosmoBase.Abstractions/CosmoBase.Abstractions.csproj
          dotnet restore src/CosmoBase.Core/CosmoBase.Core.csproj
          dotnet restore src/CosmoBase.DataServices/CosmoBase.DataServices.csproj
          dotnet restore src/CosmoBase.DependencyInjection/CosmoBase.DependencyInjection.csproj
          dotnet restore src/CosmoBase/CosmoBase.csproj
          dotnet build src/CosmoBase.Abstractions/CosmoBase.Abstractions.csproj --configuration Release
          dotnet build src/CosmoBase.Core/CosmoBase.Core.csproj --configuration Release
          dotnet build src/CosmoBase.DataServices/CosmoBase.DataServices.csproj --configuration Release
          dotnet build src/CosmoBase.DependencyInjection/CosmoBase.DependencyInjection.csproj --configuration Release
          dotnet build src/CosmoBase/CosmoBase.csproj --configuration Release
          
      # Pack all projects
      - name: Pack
        run: |
          dotnet pack src/CosmoBase.Abstractions/CosmoBase.Abstractions.csproj --configuration Release --no-build /p:Version=${{ steps.gitversion.outputs.NuGetVersion }}
          dotnet pack src/CosmoBase.Core/CosmoBase.Core.csproj --configuration Release --no-build /p:Version=${{ steps.gitversion.outputs.NuGetVersion }}
          dotnet pack src/CosmoBase.DataServices/CosmoBase.DataServices.csproj --configuration Release --no-build /p:Version=${{ steps.gitversion.outputs.NuGetVersion }}
          dotnet pack src/CosmoBase.DependencyInjection/CosmoBase.DependencyInjection.csproj --configuration Release --no-build /p:Version=${{ steps.gitversion.outputs.NuGetVersion }}
          dotnet pack src/CosmoBase/CosmoBase.csproj --configuration Release --no-build /p:Version=${{ steps.gitversion.outputs.NuGetVersion }}
        
        
        # 6. Push only when this run was triggered by a tag (v*.*.*)
      - name: Push to NuGet.org
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          dotnet nuget push src/CosmoBase/bin/Release/*.nupkg \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json